/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      screens: {
        "max-1100": { max: "1100px" },
        "max-1050": { max: "1050px" },
        "max-1000": { max: "1000px" },
        "max-950": { max: "950px" },
        "max-900": { max: "900px" },
        "max-850": { max: "850px" },
        "max-800": { max: "800px" },
        "max-750": { max: "750px" },
        "max-700": { max: "700px" },
        "max-650": { max: "650px" },
        "max-600": { max: "600px" },
        "max-550": { max: "550px" },
        "max-500": { max: "500px" },
        "max-450": { max: "450px" },
        "max-400": { max: "400px" },
      },
      colors: {
        primary: "#003459",
        seconday: "#F7DBA7",
        pinkRed: "#FF564F",
        greenLight: "#34C759",
        orangeShine: "#FF912C",
        blueSea: "#00A7E7",
        neutral100: "#00171F",
        neutral80: "#242B33",
        neutral60: "#667479",
        neutral40: "#99A2A5",
        neutral20: "#CCD1D2",
        neutral10: "##EBEEEF",
        neutral00: "#FDFDFD",
      },
      fontFamily: {
        regular: ['"regularSans"', "sans-serif"],
        bold: ['"boldSans"', "sans-serif"],
        medium: ['"mediumSans"', "sans-serif"],
      },
      fontSize: {
        heading: ["46px", { fontFamily: "regular" }],
        "heading-bold": ["46px", { fontFamily: "bold" }],
        "heading-medium": ["46px", { fontFamily: "medium" }],
        "heading-regular": ["36px", { fontFamily: "regular" }],
        "bold-36": ["36px", { fontFamily: "bold" }],
        "semibold-36": ["36px", { fontFamily: "medium" }],
        "regular-28": ["28px", { fontFamily: "regular" }],
        "bold-28": ["28px", { fontFamily: "bold" }],
        "medium-28": ["28px", { fontFamily: "medium" }],
        "regular-24": ["24px", { fontFamily: "regular" }],
        "bold-24": ["24px", { fontFamily: "bold" }],
        "semibold-24": ["24px", { fontFamily: "medium" }],
        "regular-20": ["20px", { fontFamily: "regular" }],
        "bold-20": ["20px", { fontFamily: "bold" }],
        "medium-20": ["20px", { fontFamily: "medium" }],
        "regular-16": ["16px", { fontFamily: "regular" }],
        "bold-16": ["16px", { fontFamily: "bold" }],
        "medium-16": ["16px", { fontFamily: "medium" }],
        "regular-14": ["14px", { fontFamily: "regular" }],
        "bold-14": ["14px", { fontFamily: "bold" }],
        "medium-14": ["14px", { fontFamily: "medium" }],
        "regular-12": ["12px", { fontFamily: "regular" }],
        "bold-12": ["12px", { fontFamily: "bold" }],
        "medium-12": ["12px", { fontFamily: "medium" }],
        "regular-10": ["10px", { fontFamily: "regular" }],
        "bold-10": ["10px", { fontFamily: "bold" }],
        "medium-10": ["10px", { fontFamily: "medium" }],
        "regular-8": ["8px", { fontFamily: "regular" }],
        "bold-8": ["8px", { fontFamily: "bold" }],
        "semibold-8": ["8px", { fontFamily: "medium" }],
      },

      backgroundImage: {
        hero: "url('/assets/images/bg.webp')",
        ad1: "url('/assets/images/ad.png')",
        ad2: "url('/assets/images/ad2.png')",
      },
    },
  },
  plugins: [],
};
